function functionname(){
    try{
        console.log(num1)
    }
    catch ReferenceError(msg){
     console.log(msg)   
    }
}

functionname()